# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

logo:
  image: "logo.svg"
  alt: "CREO"

# Site header

header:
  navbar:
    enable: true
    align: r
    show_title: false
    show_logo: true
    logo:
      text: ""
      height: 100 
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false


# Site footer

footer:
  copyright:
    notice: '© {year} CREO Lab. All rights reserved.'
  privacy_policy_url: '/privacy-policy/'
  design_credit: 'Web Design by CREO Team'

contact_links:
  - icon: twitter
    icon_pack: fab
    name: Twitter
    link: 'https://twitter.com/your_handle'
  - icon: youtube
    icon_pack: fab
    name: YouTube
    link: 'https://youtube.com/your_channel'
  - icon: facebook-f
    icon_pack: fab
    name: Facebook
    link: 'https://facebook.com/your_page'
  - icon: instagram
    icon_pack: fab
    name: Instagram
    link: 'https://instagram.com/your_handle'

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

assets:
  css:
    - "scss/lab.scss"   
    - "scss/footer.scss"
    - "scss/slider.scss"
    - "scss/group.scss"

  js:
    - "js/slider.js"