name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.150.0' 

on:
  push:
    branches: ["main"] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (main)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            ~/.cache/go-build
            ~/go/pkg/mod
            ${{ github.workspace }}/resources
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Install Node deps if present (for PostCSS/JS)
        run: |
          if [ -f package.json ]; then
            corepack enable || true
            if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; exit 0; fi
            if [ -f yarn.lock ]; then yarn --frozen-lockfile; exit 0; fi
            if [ -f package-lock.json ]; then npm ci; exit 0; fi
            npm i
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build site
        run: |
          hugo --minify --gc --cleanDestinationDir

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

