name: Hugo CI (test build only)

env:
  WC_HUGO_VERSION: '0.135.0'

on:
  push:
    branches:
      - '**'
      - '!main'        # 排除 master
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Test Hugo build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            ~/.cache/go-build
            ~/go/pkg/mod
            ${{ github.workspace }}/resources
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Install Node deps if present (for PostCSS/JS)
        run: |
          if [ -f package.json ]; then
            corepack enable || true
            if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; exit 0; fi
            if [ -f yarn.lock ]; then yarn --frozen-lockfile; exit 0; fi
            if [ -f package-lock.json ]; then npm ci; exit 0; fi
            npm i
          fi

      - name: Test build (no deploy)
        run: |
          hugo --minify --gc --cleanDestinationDir \
               --printI18nWarnings --printUnusedTemplates
